### ISSUE TITLE
PIDtoolbox v0.55 Error in PTload when selecting log (Linux)

### ISSUE THREAD

**Issue by abienias97** [bw1129/PIDtoolbox#86] opened 2022-06-16 14:23 UTC
Hello,

i just installed PIDtoolbox on Linux. Right after program open's up i want to select log in control panel on the right side. After selecting correct file a popup window from screenshot appears. I tried opening just this one log, unfortunately i don't have any other log to check right now. Zipped log file attached.

After clicking ok console says:

Error in PTload 

 Message:
Index exceeds matrix dimensions.
Index exceeds matrix dimensions.

Error in PTviewerUIcontrol (line 92)

Error using waitforallfiguresclosed (line 9)
Error while evaluating UIControl Callback.

After clicking ok in popup window, second popup with progress bar stays on at 0% and doesnt do anything.

Please help.

![image](https://user-images.githubusercontent.com/96074651/174090601-e71390d6-e548-4e34-93dc-317123356381.png)
[log.zip](https://github.com/bw1129/PIDtoolbox/files/8919604/log.zip)

**Comment by bw1129** [comment] 2022-06-16 14:30
Make sure log is not in main

**Comment by abienias97** [comment] 2022-06-16 14:31
> Make sure log is not in main

It is clearly not inside main folder.

**Comment by bw1129** [comment] 2022-06-16 15:25
I have no issue loading that logfile on my end

**Comment by abienias97** [comment] 2022-06-16 15:27
Are you also using linux version?

**Comment by abienias97** [comment] 2022-06-16 15:27
Are you also using linux version?

**Comment by abienias97** [comment] 2022-06-16 15:27
Are you also using linux version?

**Comment by abienias97** [comment] 2022-06-17 09:24
I have no idea what has changed but it randomly started working just fine.

**Comment by mituritsyn** [comment] 2022-08-14 18:40
works fine on Fedora. @abienias97 could you please close the issue?

**Comment by bw1129** [comment] 2022-08-14 19:13
I recommend leaving it open so others can see the solution

**Comment by mituritsyn** [comment] 2022-08-14 19:20
> I recommend leaving it open so others can see the solution

there is no solution as there weren't issue) All issues also available after closing. The problem is there is so many irrelevant opened issues so it is hard to find relevant one

**Closed** 2022-08-14 19:29 UTC
